name: ihavefriends
description: A Flutter project for IS.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=2.18.4 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  firebase_core: ^2.2.0
  firebase_auth: ^4.1.2
  json_annotation: ^4.3.0
  flutter_spinkit: ^5.1.0
  intl: ^0.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  cloud_firestore: ^4.0.5
  firebase_core: ^2.2.0
  provider: ^6.0.2
  build_runner: ^2.1.4
  json_serializable: ^6.0.1

  flutter_launcher_icons: "^0.11.0"

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon1024.png"
  min_sdk_android: 21
  web:
    generate: true
    image_path: "assets/icon/icon1024.png"
    background_color: "48c2c5"
    theme_color: "48c2c5"
    windows:
      generate: true
      image_path: "assets/icon/icon1024.png"
      icon_size: 48 # min:48, max:256, default: 48
    macos:
      generate: true
      image_path: "assets/icon/icon1024.png"

flutter:
  uses-material-design: true
  assets:
    - assets/